### ISSUE TITLE
Question: ThreadSleep. Making all API requests 1 second longer. 

### ISSUE THREAD

**Issue by Phiph** [rlsystems/TravelAppClient#2]
Is this still needed?

 https://github.com/rlsystems/TravelAppClient/blob/97164a5e9bd2bcd5319d41bee9db1f7a12086947/src/app/api/agent.ts#L31

**Comment by rlsystems** [comment]
No this is just for development purposes, I'm putting in some artificial delay so its easier to see what's going on when the app loads things

**Comment by Phiph** [comment]
Yeah fairs. 

Have a look at some open telemetry and add that into the pipeline if you wish to get more indepth idea on how the pipeline works. 

https://github.com/open-telemetry/opentelemetry-js-api
